# Generated by Django 4.2.11 on 2024-08-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('replied_to', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='profiles.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['date_sent'],
            },
        ),
    ]
