# Generated by Django 4.2.11 on 2024-06-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('replied_to', models.BooleanField(default=False)),
            ],
        ),
    ]
