# Generated by Django 4.2.11 on 2024-06-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['date_sent']},
        ),
    ]
