# Generated by Django 4.2.11 on 2024-06-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_enquiry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['date_sent'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
