# Generated by Django 4.2.11 on 2024-06-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('contact', '0003_alter_enquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='profiles.userprofile'),
        ),
    ]
