# Generated by Django 4.2.11 on 2024-05-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
